### PR TITLE
EDSC-1166 (temporarily?) change the wording that prompts user to ente…

### PR DESCRIPTION
**Pull request by mightynimble**
…r crendentials.

### CODE REVIEW

**Comment by mightynimble** [comment]
We are not gonna explicitly support NSIDC's anonymous download. Only the prompt text is changed.

**Comment by macrouch** [comment]
Can we add a test for the anonymous user?

**Comment by mightynimble** [comment]
Are you saying run the script in the test providing anonymous and email as the username/password?

**Comment by macrouch** [comment]
right, basically right the test that proves the acceptance criteria

**Comment by macrouch** [comment]
can we do that?

**Comment by mightynimble** [comment]
I didn't find a way to verify the content of the downloaded scripts. It may be even harder to run the script. (If we have existing tests, at least the innerHTML vs textContent issue can be caught.)

**Comment by mightynimble** [comment]
Last time, I depended on Kathy to manually test it for me.

**Comment by macrouch** [comment]
That's fine, I was just hoping we could add it to the automated testing

**Comment by mightynimble** [comment]
I have one more commit to make.

**Comment by macrouch** [comment]
I'm getting this when trying to run the script

```
> ./download.sh
./download.sh: line 12: syntax error near unexpected token `&'
./download.sh: line 12: `  awk '!/n5eil01u\.ecs\.nsidc\.org/' ~/.netrc &gt; $dot_netrc_tmp &amp;&amp; mv $dot_netrc_tmp ~/.netrc'```

**Comment by macrouch** [comment]
I think that might be from 1168, can you merge master into this branch to pickup the change

**Pull request merged**
