### PR TITLE
EDSC-3328: Rename 'Available from AWS Cloud' facet to 'Available in Earthdata Cloud'

### PR DESCRIPTION
**Pull request by tiagogalvao**
# Overview

### What is the feature?

Rename 'Available from AWS Cloud' facet to 'Available in Earthdata Cloud' (#1543)

### What is the Solution?

Renaming all strings and internal names

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by trevorlang — APPROVED** [review]

**Comment by macrouch** [comment]
@tiagogalvao This PR has some failing tests in the cypress tests, are you able to see that from github actions?

All the failing tests are in `search.cy.js`. All the tests that use `getByTestId('facet_item-available-from-aws-cloud')` are failing

**Comment by tiagogalvao** [comment]
Hope it works now 🤞🏻

**Review by macrouch — APPROVED** [review]
Thanks for your contributions!

**Review by trevorlang — APPROVED** [review]
Looks good to me. Thanks for contributing!

**Pull request merged**
