### PR TITLE
EDSC-1632 EDSC-1633 EDSC-1634 EDSC-1635 Handle redirection from Rever…

### PR DESCRIPTION
**Pull request by mightynimble**
…b on EDSC side.

PR on Reverb side
https://git.earthdata.nasa.gov/projects/ECHO/repos/echo-reverb-rails/pull-requests/126/overview

TODO:
modal content and css

### CODE REVIEW

**Comment by jboukes** [comment]
Why does this PR exist when I've already submitted one that does the same thing?  Mark explicitly asked me to do this work at the meeting last week.

???

**Comment by mightynimble** [comment]
The plan is to combine your or with this. I left the modal part out.

**Comment by jboukes** [comment]
I was not assigned "the modal" - I was assigned the entire EDSC side of the logic, and that is reflected in the PR that was submitted Sunday.

**Comment by jboukes** [comment]
This PR should be closed; work on the EDSC side of this ticket is under the PR I've already submitted.

**Pull request closed without merging**
