### PR TITLE
EDSC-1130 Add a test for the echoform changes.

### PR DESCRIPTION
**Pull request by mightynimble**

### CODE REVIEW

**Comment by macrouch** [comment]
This isn't working for me, is there something I have to do to get it to work?

**Comment by mightynimble** [comment]
@macrouch do a `git submodule udpate` to pick up the echoforms changes.

**Comment by macrouch** [comment]
I'm not sure if I'm doing the submodule update correctly, it isn't giving me any output. And I'm still not able to submit the service request a second time successfully.

It also looks like my recent merge gave you some merge conflicts

**Comment by mightynimble** [comment]
On bugfix/EDSC-1130 in edsc, go to ./edsc/echo forms and checkout the same branch there. "npm install" in the same dir. Then you should be able to verify it, *I think*. 

I will resolve the conflicts later. Fixtures...

**Comment by macrouch** [comment]
cool, that got it to work. Now is there anything I need to do to get everything back on master?

**Comment by mightynimble** [comment]
git checkout master in echo forms dir and the root dir of edsc. Do a "./bin/setup" just to be safe :)

**Pull request merged**
