### PR TITLE
EDSC-1553 remove config/services.yml from git history.

### PR DESCRIPTION
**Pull request by mightynimble**
This is the follow up to the EDSC-1553 PR. It removes all history refs of ```services.yml```.

### CODE REVIEW

**Comment by jboukes** [comment]
Help a guy out - what would be the best way to review this PR?  It's a bit busy due to all of the merges and I'm not sure even of the reason for removing services.yml.

**Comment by mreese84** [comment]
@mightynimble, John's question is fair. What exactly are we looking at/reviewing and why.

**Comment by mightynimble** [comment]
Really, there is nothing to look at - this should have been merged to master directly per instruction here: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

See the JIRA ticket for more info. Long story short - we are removing sensitive info from the file. (then the file needs to be appended by '.erb' to enable ENV injection.)

**Comment by mreese84** [comment]
@mightynimble are you waiting to merge this for some reason? Just curious.

**Comment by mightynimble** [comment]
Oh, yeah. I need to re-create this PR on top of the new master HEAD.

**Pull request closed without merging**
