### PR TITLE
EDSC-1441 Remove calendar events from EDSC

### PR DESCRIPTION
**Pull request by mightynimble**

### CODE REVIEW

**Comment by jboukes** [comment]
Code looks reasonable to me.  ;)

**Comment by mreese84** [comment]
@mightynimble, I'm currently waiting on approval for Status app access to test this fully. I want to make sure EDSC is just straight using the javascript widget and not the API.

**Comment by mightynimble** [comment]
We are using the API, not the javascript widget. Because we need to be albe to
 - show/hide the banner
 - show one environment's banners in another. (with cmr_env query param)

**Comment by mreese84** [comment]
@mightynimble, the status app has a "dismissable" flag that will allow users to dismiss the notification. And the cmr_env parameter wouldn't work because the Status app isn't tied to the CMR.

**Comment by mreese84** [comment]
This is no longer needed. It was taken care of in #417

**Pull request closed without merging**
