### PR TITLE
Add podaac portal

### PR DESCRIPTION
**Pull request by lewismc**
Although the EDSC team may not be in a position to accept and/or merge this code yet, I wanted to send the PR such so that it can be reviewed if the opportunity arises.

### CODE REVIEW

**Comment by mreese84** [comment]
Hey @lewismc, we're not totally ignoring this. We have a _massive_ update underway of our testing tools and leaflet along with a bit of a fire on our deployment side of things (phantomjs isn't supported anymore). So until we get that settled, nothing is going into EDSC. From the eyeball test though, this looks like it'll work just fine.

**Comment by lewismc** [comment]
Ack that’s fine, thanks for following up. I saw the tickets has been moved
to different sprint so gauged that other tasks had taken priority.
-- 

*Lewis*
Dr. Lewis J. McGibbney Ph.D, B.Sc
*Skype*: lewis.john.mcgibbney

**Comment by mreese84** [comment]
@lewismc, as mentioned at the beginning of this effort, we have made significant changes to how EDSC is setup for local development. As such, I think the most efficient path forward is to close this pull request and start new. In fact, we (EDSC) would get a lot of value if you would just completely delete the repository from your machine and start over with the forking process, following our new README to ensure it is sufficient for a new dev to follow and get running.

**Comment by lewismc** [comment]
I'll do exactly that... right now @mreese84 thanks

**Pull request closed without merging**
