### PR TITLE
EDSC-1572 Fix a typo

### PR DESCRIPTION
**Pull request by mightynimble**
This PR fixes the single granule download issue in UAT and PROD

### CODE REVIEW

**Comment by mreese84** [comment]
@mightynimble, do we need to add a test showing that the previous code didn't work? I was chatting with Doug today and he said the idea is to write a test showing that it was broken, then fix it, then write a test showing that it works.

**Comment by mightynimble** [comment]
It will fail with previous code.

**Comment by mreese84** [comment]
@mightynimble, so to be clear, and to ease some concern over the commit message... this is not an edge case. It reads like the test checks the core functionality of the feature, which is good. But this is not an edge case. This is a highly desired feature that will most certainly be used often and promoted by those that are encouraging users to switch to EDSC. Are you confident that this feature is fully tested?

**Comment by mightynimble** [comment]
Yes, I am sure it is working now. And I know it is an important feature.
The latest commit fixes a typo and the issue that Andy reported was indeed an edge case :)

**Pull request merged**
