### PR TITLE
EDSC-1298 make echo_root configurable as env variable echo_url_<env>

### PR DESCRIPTION
**Pull request by macrouch**

### CODE REVIEW

**Comment by mreese84** [comment]
@jboukes @mightynimble, have either of you had a look at this PR?

**Comment by mightynimble** [comment]
I think we don't need to merge this pr. We have talked to Doug about it. (a configurable echo_root url won't help.)

**Comment by mreese84** [comment]
@mightynimble, this ticket was reviewed this morning in the ERB and Doug seemed to think we were still going to work it.

**Comment by mightynimble** [comment]
@mreese84 ok, bring it into this sprint. I will take over after I fix all the tests for EDSC-1313.

**Pull request merged**
