### PR TITLE
EDSC-1214: Removed granule filter from href

### PR DESCRIPTION
**Pull request by jboukes**
Added code to remove the granule filter from the link returning to collection results.

### CODE REVIEW

**Comment by jboukes** [comment]
Rspec test is now also submitted ;)

**Comment by macrouch** [comment]
Can you open this pull request from your newly cloned project, and not from the fork so the tests have a chance to pass

**Comment by macrouch** [comment]
Your test doesn't fully replicate the steps from the ticket.

Steps:

1. Download a single granule
2. On the data access retrieval page, choose "Back to Search Results"
3. Click on the collection that you downloaded the granule from

For step 3 you should test that more than one granule exists in the granule list for the selected collection.

**Comment by jboukes** [comment]
>>"Can you open this pull request from your newly cloned project, and not from the fork so the tests have a chance to pass"

Conflicting requests, here - Mark asked that I continue to use the fork for this particular ticket and use the clone for all future items.

**Comment by jboukes** [comment]
>>"Your test doesn't fully replicate the steps from the ticket."

It really does, unless I am missing something.  I took advantage of an existing test that did exactly that - test a collection with multiple granules and viewing only a single granule:

```
  context 'when the user is logged in' do
    before :all do
      load_page :search, focus: downloadable_collection_id
      login
      wait_for_xhr
      **first_granule_list_item.click_link "Retrieve single granule data"**
      wait_for_xhr
    end

    after :all do
      Capybara.reset_sessions!
    end

    it 'only configures one granule' do
      **expect(page).to have_content "1 Granule"**
    end

    **it 'does not have granule filter in back url' do
      expect(find_link('Back to Search Session')[:href]).not_to include("&sgd=")
    end**

    it 'limits the data access to only the selected granule' do
      click_link 'Expand List'
      expect(page).to have_content 'FIFE_RAIN_30M.72981621.r30'
    end
  end
```

This test is specifically using this collection: https://search.earthdata.nasa.gov/search/granules?p=C179002914-ORNL_DAAC&tl=546393600!4!!

This collection has 117 granules.

So, the logic fits our needs; the test is **already** viewing a single granule out of a multi-granule collection, and I added a check to make sure the granule filter is removed from the 'back' link.  This feels like the right spot to add this test.  If you like, I could add an 'expect' for it to have 117 granules, though I'm not sure if that's really necessary.

**Pull request closed without merging**
