### PR TITLE
EDSC-1420 Add code to handle multiple subsetting agents (e.g. GDAL and HEG).

### PR DESCRIPTION
**Pull request by mightynimble**

### CODE REVIEW

**Comment by mreese84** [comment]
@mightynimble I can't get to the data access page for the collection you mentioned in chat. URS redirect is acting up on me.
screen shot 2017-05-12 at 4 13 07 pm

**Comment by mightynimble** [comment]
@mreese84 it seems to be resolved.

**Comment by mreese84** [comment]
@mightynimble nope, still seeing the same issue. It only happens when I put the cmr_env=sit parameter in the url.

**Comment by mightynimble** [comment]
Could you show me the url of your screenshot?

**Pull request merged**
