### PR TITLE
EDSC-3314: Display explore button with diabled state and tooltip

### PR DESCRIPTION
**Pull request by himanshu007-creator**
# Overview

### What is the feature?
This pr will help  the explore button to be disabled along with a tooltip when parameters are invalid.
solves https://github.com/nasa/earthdata-search/issues/1544

### What is the Solution?
I have used react bootstrap's overlaytrigger component that will show tooltip only when the conditions are met. Similarly the dropdown toggle will be disabled.

### What areas of the application does this impact?
Explore button 

List impacted areas.

# Testing

### Reproduction steps

- **Environment for testing:**
- **Collection to test with:**

1. Step 1
2. Step 2...

### Attachments

Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by macrouch** [comment]
I pulled this down and tested it, it does not disable the button, and it does not show a tooltip. 
Screen Shot 2022-10-10 at 10 01 14 AM

There are also no tests added for the new feature.

Please reviewing the [contributing file](https://github.com/nasa/earthdata-search/blob/master/CONTRIBUTING.md#commits) as well, specifically your commit message needs to match the guidelines

**Review by macrouch — CHANGES_REQUESTED** [review]
I pulled this down and tested it, it does not disable the button, and it does not show a tooltip. 
Screen Shot 2022-10-10 at 10 01 14 AM

There are also no tests added for the new feature.

Please reviewing the [contributing file](https://github.com/nasa/earthdata-search/blob/master/CONTRIBUTING.md#commits) as well, specifically your commit message needs to match the guidelines

**Comment by himanshu007-creator** [comment]
Hi @macrouch is there any way i can test the changes locally?

**Comment by macrouch** [comment]
Follow the [README.md](https://github.com/nasa/earthdata-search/blob/master/README.md) to get a local environment set up

**Comment by macrouch** [comment]
Closing due to inactivity

**Pull request closed without merging**
